#!/usr/bin/env bash
# script that configures a new Ubuntu machine with the following requirements:
#   - Install Nginx
#   - Nginx should be listening on port 80
#   - When querying Nginx at its root / with a GET request using curl, it must
#     return a page that contains the string "Holberton School"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee var/www/html/index.nginx-debian.html
sudo service nginx start
