#!/usr/bin/env bash
# script that configures a Nginx server so that /redirect_me redirects to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=_cAskH1PtmQ permanent;" /etc/nginx/sites-available/default
sudo service nginx start
