#!/usr/bin/env bash
# script that configures a Nginx server so that /redirect_me redirects to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee var/www/html/index.nginx-debian.html
sudo service nginx start
