#!/usr/bin/env bash
# script that configures a Nginx server with a custom 404 page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee var/www/html/index.nginx-debian.html
sudo service nginx start
