#!/usr/bin/env bash
# script that configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
