#!/usr/bin/env bash
# bash script that generates a MySQL dump and creates a compressed archive from it

time=$(date '+%d-%m-%Y')
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czf "$time.tar.gz" backup.sql
