#!/usr/bin/env bash
# Displays "Holberton School" 10 times and on the 9th iteration
# displays "Holberton School" and then Hi

i=1
while [ $i -le 10 ]
do
	echo "Holberton School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	((i++))
done
