#!/usr/bin/env bash
# Loops from 1 to 10:
# 	displays "bad luck" on the 4th loop iteration
#	displays "good luck" on the 8th loop iteration
#	displays "Holberton School" for all other interations

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then echo "bad luck"
	elif [ $i -eq 8 ]
	then echo "good luck"
	else
	echo "Holberton School"
	fi
	((i++))
done
