#!/usr/bin/env bash
# Loops from 1 to 20:
# 	displays "4" & "bad luck from China" on the 4th loop iteration
#	displays "9" & "bad luck from Japan" on the 9th loop iteration
#	displays "17" & "bad luck from Italy" on the 17th loop interation

i=1
while [ $i -le 20 ]
do
	if [ $i -eq 4 ]
	then echo "bad luck from China"
	elif [ $i -eq 9 ]
	then echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then echo "bad luck from Italy"
	else
	echo $i
	fi
	((i++))
done
