#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# 	  displays hours from 0 to 12
#	  displays minutes from 1 to 59

h=0
m=1
while [ $h -le 12 ]
do
	echo "Hour: $h"
	while [ $m -lt 60 ]
	do
		echo $m
		((m++))
	done
	((h++))
done
